### ISSUE TITLE
Get temperature data

### ISSUE THREAD

**Issue by tringler** [ercpe/pymax#1]
Hello,

I'm currently trying out your library and wondering how I can get the temperatures of my device. This is my testscript. It's my first Python script so this is far away from professional code :)

```
#! /usr/bin/python

from pymax.cube import *

cube = Cube('192.168.178.143')
print('Try to connect')

try:
    cube.connect()
    print('Connected')

    for room in cube.rooms:
        print("%s: - ID: %s" % (room.name, room.room_id))
        for device in room.devices:
            print("  - %s, Serial: %s, RF address: %s" % (device.name, device.serial, device.rf_address))

    # Turn on Boost
    #response = cube.set_mode_boost(1, '043e07')

    # Set manual Temperature
    #print('Set manual temperature')
    response = cube.set_mode_manual(1, '043e07', temperature=22)
    print(response.boost_duration)

    # Set Vacation Mode
    #print('Set Vacation Mode')
    #response = cube.set_mode_vacation(1, '043e07', temperature=16, end=datetime.datetime(2016, 12, 31, 12, 00, 00))

    # Set Auto Mode
    #response = cube.set_mode_auto(1, '043e07')


finally:
    cube.disconnect()
    print('Disconnected')
```

In addition to that I get these lines. Is this a known behaviour?

```
Cannot parse device configuration for type 5 (Eco button)
Cannot parse device configuration for type 4 (Shutter contact)
```

Thanks in Advance!

**Comment by vogt31337** [comment]
Hi tringler,

parse problems:
please activate logging (see import logging), and set it to debug.
Then we can see whats behind your parse exception.

get_temperature:
currently there is a bug in the code, which hinders this system in parsing L-Responds submessages (they contain the temperature). I've created a pull request with a fix.
With this fix, you can update the device list with:

`cube.get_device_list()`

and then I think you can access the devices via:

`cube.device_list[xyz].setting.temperature`

**Comment by tringler** [comment]
Thanks - In the meantime I switched to culfw. I just forgot to close the issue. Sorry.
