### ISSUE TITLE
L-Response contains multiple sub messages

### ISSUE THREAD

**Issue by anomalousmouse** [ercpe/pymax#2]
I wondered why I was only getting L-response objects for first device, then I found out that the L-response contains multiple sub messages (every 13 byes) - one for each device, see: https://github.com/Bouni/max-cube-protocol/blob/master/L-Message.md

I wish I could work out an elegant way to update the code - maybe L Response could return an array of objects, but then handle_message would have to cope with that.  Have to admit that I am a bit of a python novice and your subclassing hurts my head!

Thanks very much for the project by the way and if you could do this amend it would be greatly appreciated.

**Comment by anomalousmouse** [comment]
So I think the way do to this would be to make class LResponse a sub-class of MultiResponse instead of BaseResponse [response.py].  Hack the LResponse _parse functions to deal with multiple devices and populate an object variable 'self.devices' much like you do in the class MResponse.

Then update parse_message of Cube object in cube.py to step through variables in msg.devices much like you do for MResponse.

Do you reckon this would work?

**Comment by ercpe** [comment]
Yes, i guess i overlooked the the "A L message can consist of many submessages" part.

The `devices` property already gets updated with the data from the LResponse (https://github.com/ercpe/pymax/blob/master/src/pymax/cube.py#L199). I think it would be better to extend the `update` function in the `DeviceList` object (https://github.com/ercpe/pymax/blob/master/src/pymax/objects.py#L92) to update the additional fields.

I haven't used pymax/pymaxd much lately (kind of "works for me" state), so I probably won't work on this for a while.

**Comment by vogt31337** [comment]
I tried to fix this issue, see my pull request "Added submessage parsing for LRespones #3".

**Comment by anomalousmouse** [comment]
Great thanks - verified that this works for me.  Have also created a pull request to @vogt31337's branch which parses actual temperature for a heater (radiator) thermostat.
